### ISSUE TITLE
Unable to interact with Steam.SteamUser();

### ISSUE THREAD

**Issue by VaporFan** [scholtzm/vapor#5]
Hello scholtzm,
I'm trying to listen to event 'tradeOffers' of Steam.SteamUser(); like this but failed, the log wouldn't populate when I received new items. Please help

bot.use({
  name: 'test-steam-user',
  plugin: function(VaporAPI) {
    VaporAPI.registerHandler({
      emitter: 'steamUser',
      event: 'tradeOffers'
    }, function(count) {
      log.info("New items in our inventory: " + count);
    });
  }
});

**Comment by scholtzm** [comment]
Hello, `tradeOffers` event ([as per docs](https://github.com/seishun/node-steam/tree/master/lib/handlers/user#tradeoffers)) only returns the number of pending trade offers, not items you receive. Try to send trade offer to your bot and you'll see.
