### ISSUE TITLE
steam-user with vapor ?

### ISSUE THREAD

**Issue by VaporFan** [scholtzm/vapor#6]
Hello scholtzm,
Is it possible to using steam-user with vapor ? Please give me a hint. Thanks

**Comment by scholtzm** [comment]
It is possible, although there might be some issues. Unfortunately, SteamUser does a lot more with the client than just being a handler.

This is how I did it back in the day and it worked for my use case: https://gist.github.com/scholtzm/354b35db333df64cb520
