### ISSUE TITLE
Automatically re-login when sessions expire, emit cookies event

### ISSUE THREAD

**Issue by tayler-king** [scholtzm/vapor#7]
I believe it could be a possibility to automatically re-login when the session expires.

I know with node-steamcommunity, an event is emitted when the session fails. I do not believe the same is found within `node-steam`.

I'm looking into including this feature locally, so if I find a good way to implement it I'll submit a PR.

**Comment by scholtzm** [comment]
There is no way to detect this just from `node-steam`. You can only tell by visiting steamcommunity.com, unfortunately.

Even the official Steam client does it. 😸

**Comment by tayler-king** [comment]
Ah.. Damn. 

For now, I'm just reconnecting vapor when trades fail with expired sessions.. Guess I'll stick to that.

Cheers.

**Comment by scholtzm** [comment]
Just in case you missed it, there's a [`api.webLogOn()` method](https://github.com/scholtzm/vapor/blob/master/docs/API.md#apiweblogon).

**Comment by tayler-king** [comment]
Ah, yeah. Read that yesterday and completely forgot. Cheers!
